"""Initial migration: create all tables

Revision ID: 4d88b7344640
Revises: 
Create Date: 2026-08-08 13:32:22.698428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4d88b7344640'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'COMPLETED', name='gamestatus'), nullable=True),
    sa.Column('small_blind', sa.Integer(), nullable=False),
    sa.Column('big_blind', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('pot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_game_sessions_game_id'), 'game_sessions', ['game_id'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('total_chips', sa.Float(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    op.create_index(op.f('ix_players_player_id'), 'players', ['player_id'], unique=False)
    op.create_index(op.f('ix_players_player_name'), 'players', ['player_name'], unique=False)
    op.create_table('game_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('starting_chips', sa.Float(), nullable=False),
    sa.Column('current_chips', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_sessions.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_participants_id'), 'game_participants', ['id'], unique=False)
    op.create_table('hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('community_cards', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_sessions.game_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hands_id'), 'hands', ['id'], unique=False)
    op.create_table('hand_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('hole_cards', sa.String(), nullable=True),
    sa.Column('final_hand', sa.String(), nullable=True),
    sa.Column('hand_rank', sa.String(), nullable=True),
    sa.Column('amount_won', sa.Float(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('folded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hand_results_id'), 'hand_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hand_results_id'), table_name='hand_results')
    op.drop_table('hand_results')
    op.drop_index(op.f('ix_hands_id'), table_name='hands')
    op.drop_table('hands')
    op.drop_index(op.f('ix_game_participants_id'), table_name='game_participants')
    op.drop_table('game_participants')
    op.drop_index(op.f('ix_players_player_name'), table_name='players')
    op.drop_index(op.f('ix_players_player_id'), table_name='players')
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_game_sessions_game_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
