"""Player management endpoints (CRUD operations)

Routes:
- POST /api/players - Create/register player
- GET /api/players - List all players
- GET /api/players/{player_id} - Get player profile
- PUT /api/players/{player_id} - Update player
- DELETE /api/players/{player_id} - Delete player
"""
from fastapi import APIRouter, HTTPException, Depends
from http import HTTPStatus
from sqlalchemy.orm import Session
from app.models.player import (
    PlayerCreateRequest,
    PlayerUpdateRequest,
    PlayerProfile,
    PlayerListResponse
)
from app.db import get_db
from app.db import crud

router = APIRouter()

@router.post("", response_model=PlayerProfile, status_code=HTTPStatus.CREATED)
async def create_player(request: PlayerCreateRequest, db: Session = Depends(get_db)):
    """Create/register a new player - player_id is auto-generated"""
    # Check if email already exists
    if request.email:
        existing = crud.get_player_by_email(db, request.email)
        if existing:
            raise HTTPException(
                status_code=409,
                detail=f"Email {request.email} is already registered"
            )

    # Create player in database (player_id auto-generated by database)
    player = crud.create_player(
        db,
        player_name=request.player_name,
        email=request.email
    )

    return PlayerProfile(
        player_id=player.player_id,
        player_name=player.player_name,
        email=player.email,
        created_at=player.created_at,
        total_games=player.total_games,
        total_wins=player.total_wins,
        total_chips_won=0
    )


@router.get("", response_model=PlayerListResponse)
async def list_players(db: Session = Depends(get_db)):
    """Get list of all registered players"""
    players = crud.get_all_players(db)
    return PlayerListResponse(
        players=[PlayerProfile(
            player_id=p.player_id,
            player_name=p.player_name,
            email=p.email,
            created_at=p.created_at,
            total_games=p.total_games,
            total_wins=p.total_wins,
            total_chips_won=0
        ) for p in players],
        total_count=len(players)
    )


@router.get("/{player_id}", response_model=PlayerProfile, status_code=HTTPStatus.OK)
async def get_player(player_id: str, db: Session = Depends(get_db)):
    """Get player profile"""
    player = crud.get_player(db, player_id)
    if not player:
        raise HTTPException(
            status_code=404,
            detail=f"Player {player_id} not found"
        )

    return PlayerProfile(
        player_id=player.player_id,
        player_name=player.player_name,
        email=player.email,
        created_at=player.created_at,
        total_games=player.total_games,
        total_wins=player.total_wins,
        total_chips_won=0
    )


@router.put("/{player_id}", response_model=PlayerProfile)
async def update_player(player_id: str, request: PlayerUpdateRequest, db: Session = Depends(get_db)):
    """Update player profile"""
    player = crud.get_player(db, player_id)
    if not player:
        raise HTTPException(
            status_code=404,
            detail=f"Player {player_id} not found"
        )

    # Update fields if provided
    if request.player_name:
        if len(request.player_name) < 2 or len(request.player_name) > 100:
            raise HTTPException(
                status_code=400,
                detail="Player name must be 2-100 characters"
            )
        player.player_name = request.player_name

    if request.email is not None:
        player.email = request.email

    db.commit()
    db.refresh(player)

    return PlayerProfile(
        player_id=player.player_id,
        player_name=player.player_name,
        email=player.email,
        created_at=player.created_at,
        total_games=player.total_games,
        total_wins=player.total_wins,
        total_chips_won=0
    )


@router.delete("/{player_id}", status_code=HTTPStatus.NO_CONTENT)
async def delete_player(player_id: str, db: Session = Depends(get_db)):
    """Delete player"""
    success = crud.delete_player(db, player_id)
    if not success:
        raise HTTPException(
            status_code=404,
            detail=f"Player {player_id} not found"
        )

    return {"message": f"Player {player_id} deleted successfully"}


@router.get("/{player_id}/stats")
async def get_player_stats(player_id: str, db: Session = Depends(get_db)):
    """Get player statistics"""
    player = crud.get_player(db, player_id)
    if not player:
        raise HTTPException(
            status_code=404,
            detail=f"Player {player_id} not found"
        )

    stats = crud.get_player_statistics(db, player_id)
    return {
        "player_id": stats["player_id"],
        "player_name": stats["player_name"],
        "total_games": stats["total_games"],
        "total_wins": stats["total_wins"],
        "win_rate": stats["win_rate"],
        "total_chips": stats["total_chips"],
        "total_won": stats["total_won"]
    }
